In [26]:
import random

import pandas as pd
import requests
from tqdm.notebook import tqdm, trange

# df = gpd.read_file('../data/border/border.geojson')
# df = df.loc[df['barrier']=='fence']
storage = "/Volumes/easystore/Drones/"
flight_data = pd.concat(
    [
        chunk
        for chunk in tqdm(
            pd.read_csv(
                f"../data/all-flights-manifest.csv",
                chunksize=100000,
                dtype=str,
            ),
            desc="Loading data",
        )
    ]
)

Loading data: 0it [00:00, ?it/s]

In [27]:
flight_data.head()

,lat_map,lon_map,time,id,date,time_s,address_map,incident_id,type,department
0,32.6224144,-117.0504452,5:34pm,8f0f4842f6dbf20b94ed2df3021b5ee5,4-30-21,5:34pm,Inkopah St/ Monserate Ave,CV2105442,Traffic Collision,cvpd
1,32.6501786,-117.0879108,2:43pm,c1795c8bb73272d54f70df7f7e228004,4-30-21,2:43pm,20 Fourth Ave,CVL035567,Subject down,cvpd
2,32.63996724,-117.08270561,12:36pm,63e43c48d029a60db4a6cf8342e8a2d9,4-30-21,12:36pm,300 Block of H St,CVL035519,Lude activity,cvpd
3,32.7115419,-117.1610577,11:38am,b182a693dcd6a99609d0031ffade5dd7,4-30-21,11:38am,600 Fourth Ave,CVL035512,Domestic violence,cvpd
4,32.6274606,-117.0744953,11:30am,c347b051e39ae3a09b41234f9f254e8c,4-30-21,11:30am,700 Block of Third Ave,CVL035503,Domestic Violence,cvpd
...,...,...,...,...,...,...,...,...,...,...
12453,39.7286612,-121.8396701,6:49pm,984de7902e5ec1ce03305e8dba176b9e,8-03-23,6:49pm,Downtown Chico,2308030297,Special event,chicopd
12454,39.7286612,-121.8396701,6:32pm,b06a1166cc9a5ed873edc99fe28d833c,8-03-23,6:32pm,Downtown Chico,2308030297,Special event,chicopd
12455,39.7286612,-121.8396701,6:07pm,9f0d2ba4de499ccd4ea8c727778e8e0f,8-03-23,6:07pm,Downtown Chico,2308030297,Special event,chicopd
12456,39.6449357,-121.8163872,5:16am,2252b6a7fb38769a3cb371d2592c4f17,8-03-23,5:16am,2700 block Burdick Road,2308030048,Outside assist - missing person,chicopd
12457,39.6449357,-121.8163872,4:57am,9dff050e6b677f1a514405d52deb303e,8-03-23,4:57am,2700 block Burdick Road,2308030048,Outside assist - missing person,chicopd

In [28]:
flight_id = "3ad25ba672bf2d76400e5dd99a3706d3"
file = f"{storage}/flights/kml/{flight_id}-coordinates.csv"
flight = pd.read_csv(file)

In [30]:
flight.head()

,sequence,longitude,latitude,altitude,id,type,incident_id,address_map
0,0,-117.071663,32.617381,34.980816,3ad25ba672bf2d76400e5dd99a3706d3,Aggressive Panhandler,28961,1100 Broadway
1,1,-117.071662,32.617381,34.980816,3ad25ba672bf2d76400e5dd99a3706d3,Aggressive Panhandler,28961,1100 Broadway
2,2,-117.071668,32.617375,35.180816,3ad25ba672bf2d76400e5dd99a3706d3,Aggressive Panhandler,28961,1100 Broadway
3,3,-117.071668,32.617376,35.580816,3ad25ba672bf2d76400e5dd99a3706d3,Aggressive Panhandler,28961,1100 Broadway
4,4,-117.071668,32.617376,35.780816,3ad25ba672bf2d76400e5dd99a3706d3,Aggressive Panhandler,28961,1100 Broadway

In [32]:
for _, row in tqdm(flight.iterrows(), total=flight.shape[0]):

    url = f"https://maps.googleapis.com/maps/api/staticmap?center={row['latitude']},{row['longitude']}&zoom=30&size=600x600&maptype=satellite&key=AIzaSyATrC1i14a-LNEyLCgoe8vP31dcAduYehc"
    r = requests.get(url, allow_redirects=True)
    open(f"{storage}/images/{flight_id}/{row['sequence']}.png", "wb").write(
        r.content
    )

  0%|          | 0/902 [00:00<?, ?it/s]