In [5]:
import geopandas as gpd
import fiona
import os
import pandas as pd
import gpxpy

# Load gpx.
with open("./data/t.gpx") as f:
    gpx = gpxpy.parse(f)

points = []
for segment in gpx.tracks[0].segments:
    for p in segment.points:
        points.append({
            'time': p.time,
            'latitude': p.latitude,
            'longitude': p.longitude,
            'elevation': p.elevation,
        })
df = pd.DataFrame.from_records(points)

# fiona.drvsupport.supported_drivers['kml'] = 'rw'
# fiona.drvsupport.supported_drivers['KML'] = 'rw'
# kml_path = "/Volumes/easystore/Drones/flights"
# drone = pd.read_csv('./drone-tlkt/data/all-flights-manifest.csv')
# drone['fn'] = drone['id'].apply(lambda x: f"{kml_path}/{x}.kml")
# drone

In [22]:
import geopandas as gpd
import fiona
import os
import pandas as pd
import gpxpy

df = pd.read_csv('drone-tlkt/data/all-flights-manifest.csv')

In [46]:
fiona.drvsupport.supported_drivers['kml'] = 'rw' # enable KML support which is disabled by default
fiona.drvsupport.supported_drivers['KML'] = 'rw' # enable KML support which is disabled by default

df['date'] = pd.to_datetime(df['date'])
start_date = '2023-07-24'

di = df[df['type'].astype(str).str.contains("omestic")]

In [47]:
di

,lat_map,lon_map,time,id,date,time_s,address_map,incident_id,type,department
3,32.711542,-117.161058,11:38am,b182a693dcd6a99609d0031ffade5dd7,2021-04-30,11:38am,600 Fourth Ave,CVL035512,Domestic violence,cvpd
4,32.627461,-117.074495,11:30am,c347b051e39ae3a09b41234f9f254e8c,2021-04-30,11:30am,700 Block of Third Ave,CVL035503,Domestic Violence,cvpd
47,32.595700,-117.085936,12:30pm,6d4eabe8f91a969f5ca837dc83f80bc7,2021-04-27,12:30pm,2256 Main St.,CVL34603,Domestic Violence,cvpd
83,32.604227,-117.038524,2:40pm,fdfa09ae051e76d8945f4c717751cce7,2021-04-24,2:40pm,300 Sandstone Ct.,CVL33712,Domestic Violence,cvpd
125,32.645613,-117.087000,9:29am,026b9cb019719e47a8a81339353f1d21,2021-04-22,9:29am,100 Guava Ave,CVL32999,Domestic Violence,cvpd
...,...,...,...,...,...,...,...,...,...,...
11449,39.734089,-121.863979,11:15am,1e6ad3c28cf441c30da8f150b568e825,2022-07-16,11:15am,1400 block Nord Ave.,22-4378,Domestic violence,chicopd
11450,39.734089,-121.863979,10:49am,cc90de1451ccf8fed5d6e1ad3259337f,2022-07-16,10:49am,1400 block Nord Ave.,22-4378,Domestic violence,chicopd
11451,39.734089,-121.863979,10:29am,0144623a4e1cc4962639db37f521a7fc,2022-07-16,10:29am,1400 block Nord Ave.,22-4378,Domestic violence,chicopd
11452,39.734089,-121.863979,10:16am,e2d26e626ee4e9a982cd87c074fa904f,2022-07-16,10:16am,1400 block Nord Ave.,22-4378,Domestic violence,chicopd
11532,39.733181,-121.777570,7:46pm,19baa851157267ff2e74281baae1e0ae,2023-03-26,7:46pm,300 block Picholine Way,2023085194,Domestic Violence,chicopd

In [48]:
di['fn'] = di['id'].apply(lambda x: f"/Volumes/easystore/Drones/flights/kml/{x}.kml")

/var/folders/nq/51nwndf52yqcj9x8h10zjpg80000gn/T/ipykernel_3762/3440793394.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  di['fn'] = di['id'].apply(lambda x: f"/Volumes/easystore/Drones/flights/kml/{x}.kml")

In [49]:
compiled_flights = []
for _, row in di.iterrows():
    try:
        d = gpd.read_file(row['fn'], driver='KML')


        d['id'] = row['id']
        d['type'] = row['type']
        d['incident_id'] = row['incident_id']
        d['address_map'] = row['address_map']
        d['date'] = row['date']
        d['time'] = row['time_s']

        compiled_flights.append(d)
    except:
        print("nah")

In [50]:
compiled = pd.concat(compiled_flights)

In [51]:
compiled.to_csv('./test.csv')

In [18]:
rdf = gpd.GeoDataFrame( pd.concat( dfs, ignore_index=True) )
rdf.shape[0]

2000

In [19]:
rdf.drop_duplicates().to_file("test.geojson", driver='GeoJSON')

In [20]:
rdf.drop_duplicates()

,Name,Description,geometry,id,type,address
0,Home,,POINT Z (-117.08268 32.64000 22.10523),2adccc56aa72db328879f1fafeaafcb3,Person Down,100 Bonita Rd
1,Airdata.com,,"LINESTRING Z (-117.08268 32.64000 22.10523, -1...",2adccc56aa72db328879f1fafeaafcb3,Person Down,100 Bonita Rd
2,Home,,POINT Z (-117.07166 32.61742 34.82301),e90e2d6bae17030e1e1d9c6dcca0b4a2,Unknown Problem,500 Anita St.
3,Airdata.com,,"LINESTRING Z (-117.07166 32.61742 34.82301, -1...",e90e2d6bae17030e1e1d9c6dcca0b4a2,Unknown Problem,500 Anita St.
4,Home,,POINT Z (-117.08270 32.63998 22.13710),eaaec83162027023bf4a950deaa8a919,Weapon Threat,Broadway/ E St.
...,...,...,...,...,...,...
1995,Airdata.com,,"LINESTRING Z (-117.07164 32.61742 34.79365, -1...",4c8d2d1e7a90dc8bc0a36177e31a5c5c,Collision,I-5/ Palomar St.
1996,Home,,POINT Z (-117.08273 32.63996 22.14651),45d5862d6b272aacba5cc5c12ea1b6d3,Auto Theft,745 H
1997,Airdata.com,,"LINESTRING Z (-117.08273 32.63996 22.14651, -1...",45d5862d6b272aacba5cc5c12ea1b6d3,Auto Theft,745 H
1998,Home,,POINT Z (-117.07166 32.61745 34.88751),be2db64e0805627e3cc250db4c92ccba,Welfare Check,1400 Hilltop Dr.
1999,Airdata.com,,"LINESTRING Z (-117.07166 32.61745 34.88751, -1...",be2db64e0805627e3cc250db4c92ccba,Welfare Check,1400 Hilltop Dr.